### ISSUE TITLE
show highway=busway

### ISSUE THREAD

**Issue by matkoniecz** [ENT8R/streetcomplete-mapstyle#147] opened 2024-07-18 05:12 UTC
see https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbusway

requested in https://github.com/streetcomplete/StreetComplete/issues/5749

**Comment by matkoniecz** [comment] 2024-07-18 05:12
@Joxit are there plans/chances to include `highway=busway` in Jawg vector tiles?

**Comment by matkoniecz** [comment] 2024-07-18 07:30
if implemented - reopen https://github.com/streetcomplete/StreetComplete/issues/5749 or extract quests from it (surface quest?)

**Comment by Joxit** [comment] 2024-07-18 09:50
Hi there, thank you for your feedback. After a quick review of the tag, we decide to add it to our tileset `streets-v2`.

I will be get back to you when it's done :smile:

**Comment by Joxit** [comment] 2024-07-18 09:50
Could you assign the issue to me ?

**Comment by matkoniecz** [comment] 2024-07-18 09:56
Done!

**Comment by Joxit** [comment] 2024-07-24 09:13
Hi there, we did the release for `highway=busway` yesterday, the new tiles are rolling up gradually.

You can check the documentation for a custom styling: https://www.jawg.io/docs/apidocs/maps/streets-v2/#road

The data will be available in the `road` layer, the assigned class is `service` and the type is `busway`.

In this example `Carrefour de Pompadour` is a busway + bridge. 

![Screenshot_20240724-110816](https://github.com/user-attachments/assets/112b676d-59ad-4780-9bf6-fa0cb17343ab)

**Comment by matkoniecz** [comment] 2024-07-24 12:23
So it sounds like map style changes are not needed...

**Comment by mnalis** [comment] 2024-07-24 12:59
Interestingly, for me that [Carrefour de Pompadour](https://www.openstreetmap.org/way/79265103) is shown correctly (as dashed road) on https://streetcomplete.github.io/streetcomplete-mapstyle/ (Tangram StreetComplete test), so Jawg vector tiles definitely work nicely:

![chrome_screenshot_streetcomplete github io_tangram](https://github.com/user-attachments/assets/d54abeb8-3118-49f1-9029-32643ca5946f)

but **_not_** on https://streetcomplete.app/map-jawg/ (MapLibre) - there only grey bridge outline is shown.

 ![chrome_screenshot_streetcomplete app_maplibr](https://github.com/user-attachments/assets/c67b2469-7e4f-4401-bd03-c768b0541824)

Unfortunately that MapLibre web map version does not allowing showing/editing used style (like the Tangram web test version allows), so it's hard to say why it doesn't seem to render it, but I guess should be mapstyle related.

**Comment by Joxit** [comment] 2024-07-24 13:10
I have the busway on the maplibre example too.

Could you try the MapLibre version on a private tab or without cache ?

Don't forget, some tiles can be in your browser cache and some other are still outdated on some of our datacenters.

**Comment by mnalis** [comment] 2024-07-24 14:01
> I have the busway on the maplibre example too.

It was in a private window, _and_ with F12 / `disable cache`...  However, you are correct, busway does show there too when I zoom in a little more:

![chrome_screenshot_streetcomplete app_zoom2](https://github.com/user-attachments/assets/b92a7f38-7839-4921-b5cc-c3aa6ae63c35) ![chrome_screenshot_streetcomplete app_zoom1](https://github.com/user-attachments/assets/3bd33cb8-bfc1-4774-97d1-1cbafd2f73d6)

What threw me off is that [highway=service](https://www.openstreetmap.org/way/542990692) south of that roundabout is rendered normally at the same zoom level that `highway=busway` isn't. Is that intentional or?

**Comment by matkoniecz** [comment] 2024-07-24 14:07
AFAIK maplibre counts zoom levels in a different way...

If you zoom out on Tangram, will busways disappear before other service roads?

**Comment by mnalis** [comment] 2024-07-24 15:34
> If you zoom out on Tangram, will busways disappear before other service roads?

It is hard to say -- both seem to remain visible on Tangram even when I zoom out so much that the roads are barely recognizable on the map. It's only on MapLibre style that the issue happens when zoomed in. Perhaps it has custom zoom override for `highway=service` but not for `highway=busway`? 

Anyway, it does not seem to be Jawg related, but a StreetComplete MapLibre style issue.

**Comment by westnordost** [comment] 2024-07-24 21:02
The MapLibre style looks correct to me. Excerpt:

```
...
{
  "id": "roads-service",
  "source": "jawg-streets",
  "source-layer": "road",
  "filter": [
    "all",
    ["in", ["get", "class"], ["literal", ["service", "driveway"]]],
    ["==", ["geometry-type"], "LineString"],
    ["!", ["in", ["get", "structure"], ["literal", ["bridge", "tunnel"]] ]]
  ],
  "type": "line",
  "paint": {
    "line-color": "#fff",
    "line-width": ["interpolate", ["exponential", 2], ["zoom"], 13.0, 0.5, 16.0, 3.0, 24.0, 768.0],
    "line-opacity": ["interpolate", ["exponential", 2], ["zoom"], 14.0, 0.0, 15.0, 1.0]
  },
  "layout": {"line-cap": "round", "line-join": "round"}
},
...
```

i.e. all class=driveway and class=service should be covered. There is no logic in the style that differentiates between busways and other service roads.

**Comment by westnordost** [comment] 2024-07-24 21:15
Anyway, I can also not reproduce this on https://streetcomplete.app/map-jawg/, so, closing. Thanks for adding highway=busway to Jawg!

**Closed as completed by westnordost** 2024-07-24 21:15 UTC

**Comment by mnalis** [comment] 2024-07-25 04:22
Now it works for me in MapLibre too. Perhaps some zoom levels were not yet rendered, leading to the issue...

**Comment by Joxit** [comment] 2024-07-25 06:11
You are welcome 😊

Thank you for your feedback again!
