### ISSUE TITLE
Translated names are displayed in the foreign language (English)

### ISSUE THREAD

**Issue by Etua** [ENT8R/streetcomplete-mapstyle#106] opened 2021-10-09 13:44 UTC
At least the names of the seas are displayed in English rather than a local language despite carrying the appropriate tags in OSM.

**Comment by westnordost** [comment] 2021-10-09 13:49
Can you show a concrete example with screenshot?

**Comment by Etua** [comment] 2021-10-09 15:32
![Screenshot_20211009-172858_1](https://user-images.githubusercontent.com/13040148/136664818-b85e8417-0414-48ea-a607-6a14067d3fc5.png)

**Comment by matkoniecz** [comment] 2021-10-09 15:38
Note that location differs from https://www.openstreetmap.org/node/305640277

Also, `name` of https://www.openstreetmap.org/node/305640277 is actually for some reason in Polish. It seems that Jawg is using some external/own data? Is there OSM object at position matching Jawg label?

**Comment by westnordost** [comment] 2021-10-09 16:15
> Is there OSM object at position matching Jawg label?

No. There is only https://www.openstreetmap.org/way/127101946#map=11/56.5457/18.5789

So my guess is that the localization information is missing on those place names that are not from OSM. 

In other words, everything is ok with this style, the issue is the data. Closing this and pinging @Joxit , in case he wants to look into that.

**Closed as completed** 2021-10-09 16:15 UTC

**Comment by Joxit** [comment] 2021-10-09 17:02
Hi there,

Yes seas and ocean are not from OSM, we built our own datasets in order to have the best viewing experience. Checkout our blog post about this: https://blog.jawg.io/earths-oceans-and-seas/

So the default language for oceans and seas is English and we do not support Polish yet.
