### ISSUE TITLE
Render bus/tram stops

### ISSUE THREAD

**Issue by rugk** [ENT8R/streetcomplete-mapstyle#59] opened 2018-03-13 10:20 UTC
It would be nice to have at least a small icon for bus/tram stops.

These help for the orientation, especially when you are travelling in a tram/bus, and solve quests from the inside there. When GPS is not 100% correct, you can then estimate where you are

**Comment by matkoniecz** [comment] 2018-03-13 11:03
duplicate of #41

> It is also expected to read at least readme. See https://github.com/ENT8R/streetcomplete-mapstyle/blob/master/README.md#what-should-not-be-added for start.

**Comment by rugk** [comment] 2018-03-13 11:19
But we need some more orientation stuff. It is no POI (maybe a point or so, but also mapped as area or so) and generally I think excluding POIs at all is not useful.

And the other things do not apply:
> No elements which have no relation to the quests of StreetComplete

It has a relation, even some quests, but that does not matter, too AFAIK, yet again.

**Comment by ENT8R** [comment] 2018-03-13 14:25
> No elements which have no relation to the quests of StreetComplete
> >It has a relation, even some quests, but that does not matter, too AFAIK, yet again.

I actually think that this **does** matter... IMO they can be shown, but they should not be too obtrusive
@westnordost what is your opinion on this?

**Comment by westnordost** [comment] 2018-03-14 10:29
My opinion is that they should not be shown.

**Closed** 2018-04-15 12:03 UTC
