### ISSUE TITLE
One-way road showing an arrow in the wrong direction

### ISSUE THREAD

**Issue by bxl-forever** [ENT8R/streetcomplete-mapstyle#145] opened 2023-08-24 13:52 UTC
I came across a strange rendering issue here.

[Way 226693562](https://www.openstreetmap.org/way/226693562) is an ordinary one-way residential street.

osm-carto properly renders it as going to the west.
![osmcarto_west](https://github.com/streetcomplete/streetcomplete-mapstyle/assets/23359667/131acda1-dcba-4b53-a1e9-bd7630998f49)

StreetComplete renders it as going to the east.
![sc_east](https://github.com/streetcomplete/streetcomplete-mapstyle/assets/23359667/5ee0511f-ce9c-49ac-aff7-ba30502d0b48)

As far as I can see in the history, the way itself has been untouched since 2021, and the street has been one-way since 2013 (never reversed).

Can it be a rendering issue?

**Comment by matkoniecz** [comment] 2023-08-24 13:57
What is happening with other oneway roads? Is only this one affected?

**Comment by bxl-forever** [comment] 2023-08-24 14:18
Other roads look fine.

**Comment by matkoniecz** [comment] 2023-08-24 15:38
I am looking at it https://play.tangram.city/?#18.91250/50.82054/364.40677 but I cannot figure out how to look at geometry specifics (direction, start, end).

I got .pbf tile but not sure how to decode it.

**Comment by ENT8R** [comment] 2023-08-24 16:33
I was able to extract the geometry of the road from the PBF tile as a GeoJSON (Nodes at the start and end of the road added by me):
```geojson
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            4.404809474945068,
            50.818950662094494
          ],
          [
            4.404814839363098,
            50.81898878938898
          ],
          [
            4.404853731393814,
            50.819143840065806
          ],
          [
            4.405127316713333,
            50.81970896577053
          ],
          [
            4.40538614988327,
            50.82016394206548
          ],
          [
            4.405439794063568,
            50.82021816613272
          ],
          [
            4.406409412622452,
            50.82038761593702
          ],
          [
            4.408504217863083,
            50.820800223639
          ],
          [
            4.408531039953232,
            50.820829877029496
          ],
          [
            4.4085900485515594,
            50.820906975756714
          ]
        ]
      },
      "properties": {
        "class": "street",
        "name": "Rue des Trois Ponts - Driebruggenstraat",
        "name_fr": "Rue des Trois Ponts",
        "name_nl": "Driebruggenstraat",
        "oneway": true,
        "type": "residential"
      },
      "id": 41
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
           4.404809474945068,
           50.818950662094494
        ]
      },
      "properties": {
        "description": "Start"
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          4.4085900485515594,
          50.820906975756714
        ]
      },
      "properties": {
        "description": "End"
      }
    }
  ]
}
```

The tile delivered by Jawg obviously reverses the geometry for the eastern part of the road (after crossing with "Avenue Josse Smets - Josse Smetslaan") because the two roads (with different properties such as opposite oneways) are treated as the same road with only a single geometry being delivered (probably caused by pre-processing and merging the two roads because their names are the same).

**Comment by matkoniecz** [comment] 2023-08-24 16:37
> I was able to extract the geometry of the road from the PBF tile as a GeoJSON (Nodes at the start and end of the road added by me):

how this can be done?

pinging @Joxit - it seems that Jawg becomes confused by two `oneway` roads with matching name but opposite direction and processes data too aggressively

**Comment by ENT8R** [comment] 2023-08-24 16:37
The same does also happen to the road further south: "Avenue Josse Smets - Josse Smetslaan" is also treated as a single road even though it should be two separate roads with distinct properties:
```geojson
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            4.4063785672187805,
            50.818950662094494
          ],
          [
            4.40638929605484,
            50.819575098530606
          ],
          [
            4.406409412622452,
            50.82038761593702
          ]
        ]
      },
      "properties": {
        "class": "street",
        "name": "Avenue Josse Smets - Josse Smetslaan",
        "name_fr": "Avenue Josse Smets",
        "name_nl": "Josse Smetslaan",
        "oneway": true,
        "type": "residential"
      },
      "id": 36
    }
  ]
}
```

**Comment by ENT8R** [comment] 2023-08-24 16:43
> how this can be done?

I wrote a script (using [@mapbox/vector-tile](https://github.com/mapbox/vector-tile-js) and [pbf](https://github.com/mapbox/pbf)) that does this for me:

<details>
<summary>Expand to see code</summary>

This code downloads the tile at `16/33570/21991` and extracts the GeoJSON description of a specific property using its name
```javascript
import { VectorTile } from '@mapbox/vector-tile';
import Protobuf from 'pbf';

const accessToken = JAWG_ACCESS_TOKEN;
const url = `https://tile.jawg.io/streets-v2/16/33570/21991.pbf?access-token=${accessToken}`; 

fetch(url).then(response => {
    if (response.ok) return response.arrayBuffer();
    else throw new Error(`${response.status} ${response.statusText} (${response.url})`);
}).then(buffer => new VectorTile(new Protobuf(buffer))
).then(tile => {
    const layer = tile.layers.road;
    for (let i = 0; i < layer.length; i++) {
        const feature = layer.feature(i);
        if (feature.properties.name == 'Rue des Trois Ponts - Driebruggenstraat') {
            console.log(JSON.stringify(feature.toGeoJSON(33570, 21991, 16), null, 2));
        }
    }
});
```

</details>

**Comment by Joxit** [comment] 2023-09-10 06:43
Hi there, thank you for the report :smile:.
This is caused by a regression introduced early August. We will fix this ASAP.

**Comment by Joxit** [comment] 2023-09-29 20:21
Little update, the fix has been release two days ago. it's fully live by now :)

**Comment by westnordost** [comment] 2023-10-03 19:38
Nice, so this can be closed then!

**Closed as completed by westnordost** 2023-10-03 19:38 UTC
Labels: blocked
